name: Deploy to infra repo

on:
  push:
    branches: [ main ]

jobs:
  pr_to_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: "thehivebot/infrastructure"
          path: "infrastructure"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
        run: |
          cd infrastructure
          git config --local user.email "bot@thehivebot.com"
          git config --local user.name "hive-bot"
          git checkout -b deploy-hive-$GITHUB_SHA
          mkdir imagetags || true
          echo "$GITHUB_SHA" >imagetags/hive-sha
          git add .
          git commit -m "Deploy $GITHUB_SHA"
          git push --set-upstream origin deploy-hive-$GITHUB_SHA
          gh pr create --title "Deploy Hive $GITHUB_SHA" --body "Deploy $GITHUB_SHA of Hive" --repo github.com/thehivebot/infrastructure